# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{transient}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["C. Jason Harrelson (midas)"]
  s.date = %q{2010-03-18}
  s.description = %q{Provides an API for making any ActiveRecord object transient.  In addition, provides functionality for models where only a single instance of the model can be current at one time.}
  s.email = %q{jason@lookforwardenterprises.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/date_time_extensions.rb",
     "lib/transient.rb",
     "lib/transient/active_record_extensions.rb",
     "script/console",
     "spec/database.yml",
     "spec/date_time_extensions_spec.rb",
     "spec/single_active_transient_shared_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/transient/active_record_extensions_spec.rb",
     "spec/transient_shared_spec.rb",
     "spec/transient_spec.rb",
     "transient.gemspec"
  ]
  s.homepage = %q{http://github.com/midas/transient}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Provides an API for making any ActiveRecord object transient.}
  s.test_files = [
    "spec/date_time_extensions_spec.rb",
     "spec/single_active_transient_shared_spec.rb",
     "spec/spec_helper.rb",
     "spec/transient/active_record_extensions_spec.rb",
     "spec/transient_shared_spec.rb",
     "spec/transient_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.3"])
      s.add_dependency(%q<activesupport>, [">= 2.3"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.3"])
    s.add_dependency(%q<activesupport>, [">= 2.3"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

